name: Build and Push Docker to ECR

on:
  push:
    paths:
      - 'project1/**'
      - 'project2/**'
  pull_request:
    paths:
      - 'project1/**'
      - 'project2/**'

jobs:
  build-and-push-project1:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'project1') || contains(github.event.pull_request.title, 'project1') || contains(github.event.pull_request.body, 'project1')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image for project1
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/project1:latest"
          docker build -t $IMAGE_URI ./project1
          echo $IMAGE_URI > image-uri-project1.txt

      - name: Push Docker image to ECR for project1
        run: |
          IMAGE_URI=$(cat image-uri-project1.txt)
          docker push $IMAGE_URI

  build-and-push-project2:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'project2') || contains(github.event.pull_request.title, 'project2') || contains(github.event.pull_request.body, 'project2')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image for project2
        run: |
          IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/project2:latest"
          docker build -t $IMAGE_URI ./project2
          echo $IMAGE_URI > image-uri-project2.txt

      - name: Push Docker image to ECR for project2
        run: |
          IMAGE_URI=$(cat image-uri-project2.txt)
          docker push $IMAGE_URI
